GET http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvdGF0byIsImlkIjoiNjcxNmMyNDRiMGEyZWQxMTEwOTU5M2EwIiwiaWF0IjoxNzI5NjI2OTMyfQ.fsxpNLngpT0mp2DqVEFjfGwBfcavvjqkWAIjdya405Y

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Nguyen Van A",
    "password": "testpassword",
    "username": "nguyenvana",
    "email": "nguyenvana@gmail.com",
    "phoneCode": "+84",
    "phoneNumber": "0987654321"
}